apiVersion: v1
kind: Pod
metadata:
  name: jkwong-deployer
spec:
  containers:
    - name: jkwong-deployer
      image: lachlanevenson/k8s-kubectl
      imagePullPolicy: Always
      tty: true
      stdin: true
      command: [ "/bin/bash", "-c" ]
      args: [ "kubectl get secrets {{ .Values.hs256-key.secretName}} ||  kubectl create secret generic {{ .Values.hs256-key.secretName }} --from-literal=key=`cat /dev/urandom | env LC_CTYPE=C tr -dc 'a-zA-Z0-9' | fold -w 256 | head -n 1 | xargs echo -n` "]
      volumeMounts:
        - mountPath: "/var/run/docker.sock"
          name: docker-socket
          readOnly: false
        - mountPath: "/var/run/secrets/bluemix-api-key"
          name: bluemix-api-key
      env:
      - name: BX_SPACE
        valueFrom:
          configMapKeyRef:
            name: bluemix-target
            key: bluemix-space
      - name: BX_API_ENDPOINT
        valueFrom:
          configMapKeyRef:
            name: bluemix-target
            key: bluemix-api-endpoint
  volumes:
    - name: docker-socket
      hostPath:
          path: /var/run/docker.sock
    - name: bluemix-api-key
      secret:
          secretName: bluemix-api-key

